[project]
name = "pyscqed"
version = "0.15.0"
description = "Python Superconducting Circuit Quantum Electrodynamics Simulation Package"
authors = [
    {name = "Louis Fry-Bouriaux"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "scipy (>=1.17.1,<2.0.0)",
    "sympy (>=1.14.0,<2.0.0)",
    "graphviz (>=0.21,<0.22)",
    "pydot (>=4.0.1,<5.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "progress (>=1.6.1,<2.0.0)",
    "qutip (>=5.2.3,<6.0.0)",
    "networkx (<3.6.1)"
]

[tool.poetry.group.dev.dependencies]
coverage = "^7.2.2"
jupyter = "^1.0.0"
jupytext = "^1.14.5"
pytest = "^9.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
