name: CI

on:
  push:
    branches: '*'

jobs:
  tests:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
          python-version: ${{ matrix.python-version }}
    - uses: snok/install-poetry@v1
    - run: sudo apt-get install -y graphviz
    - name: Run unit tests
      run: |
        poetry install
        poetry run pytest tests

  examples:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
          python-version: ${{ matrix.python-version }}
    - uses: snok/install-poetry@v1
    - run: sudo apt-get install -y graphviz
    - name: Run examples
      run: |
        poetry install
        cd examples
        poetry run python transmon-example.py
        poetry run python fluxonium-example.py
        poetry run python averin-coupler.py
        poetry run python resonator-example.py
        poetry run python local-basis-example.py
        poetry run python jpsq-example.py
        poetry run python csfq-example.py
        poetry run python fluxonium-atom.py
